root_domain: "domek"
server_ip: "192.168.10.217"
install_path: "/opt/homelab"

# Override defaults for this server
timezone: "Europe/Warsaw"
dns_ports:
  - "{{ dns_port }}:{{ dns_port }}/tcp"
  - "{{ dns_port }}:{{ dns_port }}/udp"
  - "{{ pihole_web_port }}:80"

# Arch Linux specific
package_manager: "pacman"
docker_packages:
  - docker
  - docker-compose
  - python-docker
  - python-requests
  - ldns